###############
# localhost testing
# 

version: "3"
services:
  app:
    image: technomada/core-auth
    environment:
      - PORT=3111
      - SECURE=false # when testing in localhost
    volumes:
      - ./config.js:/app/config.js
    ports:       
      - 3111:3111
    working_dir: /app
    restart: always

networks:
  default:
    external:
      name: master
